//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteCDMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADOS()
        {
            this.CIDADES = new HashSet<CIDADES>();
        }
    
        public short IDEstados { get; set; }
        public string Estado { get; set; }
        public string Sigla { get; set; }
        public short IDPais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIDADES> CIDADES { get; set; }
        public virtual PAISES PAISES { get; set; }
    }
}
