//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteCDMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOS
    {
        public short IDMedico { get; set; }
        public string CRM { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Email { get; set; }
        public bool Convenio { get; set; }
        public bool Clinica { get; set; }
        public string Website { get; set; }
        public short IDCidade { get; set; }
        public short IDEspecialidade { get; set; }
    
        public virtual CIDADES CIDADES { get; set; }
        public virtual ESPECIALIDADES ESPECIALIDADES { get; set; }
    }
}
